name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh

      - name: Git config
        run: |
          git config --global user.email "carmenfgdev@gmail.com"
          git config --global user.name "CarmenFGDev"

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy -- -r git@github.com:CarmenFGDev/modulo7-cloud-ejercicio2.git
